[package]
name = "pba-assignment"
version = "0.1.0" 
edition = "2021"

[dependencies]
bip32 = "0.4.0"
blake2 = "0.10.6"
hex = "0.4.3"
#hex-literal = "0.3.4"
rand_core = { version = "0.6", features = ["std"]}